In [ ]:
import csv
import pandas as pd

with open('/content/Carnids Farm Sales.csv', 'r') as file:
    reader = csv.reader(file, delimiter=';')

    for row in reader:
        print(row)

['Date', 'Customer ID', 'Customer Name', 'City', 'Product Category', 'Quantity', 'Unit Cost', 'Unit Price', 'Total Revenue', 'New Customer', 'Delivery Days', 'Payment Method', 'Order Frequency', 'First Purchase Date', 'Last Purchase Date']
['24/11/23', 'CID0001', 'Customer 1', 'San Antonio', 'Packaged Foods', '8', '68.28', '85.35', '682.8', 'Yes', '3', 'Credit Card', 'Quarterly', '28/01/23', '20/04/23']
['27/02/23', 'CID0002', 'Customer 2', 'Houston', 'Vegetables', '6', '16.52', '20.646', '134.2', 'Yes', '2', 'Online Payment', 'Monthly', '05/02/23', '13/02/23']
['13/01/23', 'CID0003', 'Customer 3', 'Phoenix', 'Dairy', '19', '30.4', '38', '722', 'Yes', '1', 'Online Payment', 'Monthly', '05/01/23', '12/01/23']
['15/01/24', 'CID0004', 'Customer 4', 'San Antonio', 'Fruits', '3', '37.15', '46.44', '139.32', 'No', '3', 'Online Payment', 'Weekly', '24/12/23', '09/01/24']
['21/05/23', 'CID0005', 'Customer 5', 'Chicago', 'Bakery', '8', '38.68', '48.35', '386.8', 'Yes', '1', 'Online Payment', 'Weekly', '02/02/23', '20/02/23']
['06/05/23', 'CID0006', 'Customer 6', 'Phoenix', 'Bakery', '2', '35.04', '43.8', '87.6', 'Yes', '2', 'Debit Card', 'Monthly', '23/03/23', '19/04/23']
['25/04/23', 'CID0007', 'Customer 7', 'Phoenix', 'Meat', '8', '75.02', '93.77', '750.16', 'Yes', '2', 'Debit Card', 'Monthly', '22/04/23', '22/04/23']
['13/03/23', 'CID0008', 'Customer 8', 'San Antonio', 'Vegetables', '13', '56.6', '70.75', '919.75', 'Yes', '2', 'Credit Card', 'Monthly', '04/03/23', '07/03/23']
['13/01/24', 'CID0009', 'Customer 9', 'Los Angeles', 'Fruits', '6', '45.58', '56.97', '370.3', 'Yes', '1', 'Cash', 'Monthly', '22/02/23', '10/10/23']
['22/02/23', 'CID0010', 'Customer 10', 'Chicago', 'Vegetables', '2', '4.8', '6.006', '9.01', 'Yes', '1', 'Cash', 'Monthly', '01/01/23', '23/01/23']
['13/12/23', 'CID0011', 'Customer 11', 'San Antonio', 'Fruits', '6', '72.35', '90.44', '542.64', 'Yes', '2', 'Credit Card', 'Quarterly', '21/10/23', '22/10/23']
['15/01/24', 'CID0012', 'Customer 12', 'Chicago', 'Meat', '19', '72.78', '90.98', '1728.62', 'Yes', '1', 'Cash', 'Weekly', '26/05/23', '09/09/23']
['07/10/23', 'CID0013', 'Customer 13', 'Chicago', 'Meat', '16', '62.5', '78.13', '1250.08', 'Yes', '3', 'Credit Card', 'Quarterly', '29/08/23', '01/09/23']
['14/02/23', 'CID0014', 'Customer 14', 'Phoenix', 'Bakery', '8', '0.96', '1.2', '9.6', 'Yes', '2', 'Debit Card', 'Quarterly', '31/01/23', '06/02/23']
['30/10/23', 'CID0015', 'Customer 15', 'Houston', 'Vegetables', '0', '4.46', '5.58', '2.79', 'No', '2', 'Online Payment', 'One Time', '14/08/23', '17/10/23']
['05/08/23', 'CID0016', 'Customer 16', 'Chicago', 'Beverages', '16', '18.33', '22.91', '366.56', 'Yes', '2', 'Online Payment', 'Quarterly', '29/03/23', '02/07/23']
['17/01/23', 'CID0017', 'Customer 17', 'Philadelphia', 'Bakery', '9', '10.86', '13.57', '122.13', 'No', '3', 'Debit Card', 'Monthly', '06/01/23', '09/01/23']
['16/01/23', 'CID0018', 'Customer 18', 'Phoenix', 'Vegetables', '13', '32.14', '40.18', '522.34', 'Yes', '4', 'Online Payment', 'Monthly', '02/01/23', '08/01/23']
['17/02/23', 'CID0019', 'Customer 19', 'Los Angeles', 'Bakery', '11', '73.84', '92.3', '1015.3', 'No', '4', 'Online Payment', 'One Time', '17/01/23', '22/01/23']
['22/04/23', 'CID0020', 'Customer 20', 'Houston', 'Beverages', '13', '37.98', '47.47', '617.11', 'No', '4', 'Cash', 'One Time', '21/04/23', '22/04/23']
['30/04/23', 'CID0021', 'Customer 21', 'Philadelphia', 'Dairy', '10', '1.46', '1.83', '18.3', 'Yes', '3', 'Debit Card', 'One Time', '03/03/23', '17/03/23']
['16/09/23', 'CID0022', 'Customer 22', 'Philadelphia', 'Dairy', '4', '22.9', '28.63', '114.52', 'Yes', '4', 'Cash', 'One Time', '28/02/23', '07/03/23']
['05/11/23', 'CID0023', 'Customer 23', 'Los Angeles', 'Dairy', '6', '3.95', '4.94', '29.64', 'Yes', '3', 'Cash', 'One Time', '03/02/23', '16/07/23']
['14/01/23', 'CID0024', 'Customer 24', 'Houston', 'Dairy', '7', '3.29', '4.11', '28.77', 'No', '2', 'Online Payment', 'Quarterly', '07/01/23', '08/01/23']
['15/10/23', 'CID0025', 'Customer 25', 'Phoenix', 'Packaged Foods', '5', '22.34', '27.93', '139.65', 'Yes', '2', 'Online Payment', 'One Time', '09/09/23', '30/09/23']
['12/04/23', 'CID0026', 'Customer 26', 'New York', 'Fruits', '16', '24.57', '30.712', '506.75', 'Yes', '2', 'Debit Card', 'Quarterly', '10/01/23', '28/01/23']
['02/01/24', 'CID0027', 'Customer 27', 'Houston', 'Packaged Foods', '13', '63.06', '78.82', '1024.66', 'Yes', '4', 'Online Payment', 'Weekly', '23/10/23', '09/11/23']
['29/11/23', 'CID0028', 'Customer 28', 'Los Angeles', 'Packaged Foods', '19', '78', '97.5', '1852.5', 'No', '3', 'Online Payment', 'One Time', '19/11/23', '19/11/23']
['26/12/23', 'CID0029', 'Customer 29', 'Philadelphia', 'Packaged Foods', '10', '29.95', '37.44', '374.4', 'No', '4', 'Debit Card', 'One Time', '18/12/23', '22/12/23']
['07/10/23', 'CID0030', 'Customer 30', 'Phoenix', 'Dairy', '10', '34.54', '43.17', '431.7', 'No', '2', 'Online Payment', 'Quarterly', '28/01/23', '19/09/23']
['03/08/23', 'CID0031', 'Customer 31', 'Houston', 'Beverages', '11', '67.65', '84.56', '930.16', 'Yes', '3', 'Cash', 'Weekly', '08/02/23', '08/06/23']
['23/04/23', 'CID0032', 'Customer 32', 'New York', 'Meat', '7', '21.74', '27.18', '190.26', 'Yes', '1', 'Debit Card', 'Quarterly', '20/01/23', '19/04/23']
['18/08/23', 'CID0033', 'Customer 33', 'New York', 'Meat', '18', '12.85', '16.06', '289.08', 'Yes', '1', 'Online Payment', 'Quarterly', '27/07/23', '31/07/23']
['29/10/23', 'CID0034', 'Customer 34', 'Chicago', 'Fruits', '4', '68.3', '85.38', '341.52', 'Yes', '4', 'Credit Card', 'One Time', '16/10/23', '28/10/23']
['23/05/23', 'CID0035', 'Customer 35', 'Chicago', 'Dairy', '2', '4.1', '5.13', '10.26', 'Yes', '3', 'Debit Card', 'Monthly', '19/03/23', '18/05/23']
['04/01/23', 'CID0036', 'Customer 36', 'San Antonio', 'Dairy', '14', '49.73', '62.16', '870.24', 'Yes', '2', 'Debit Card', 'Monthly', '01/01/23', '04/01/23']
['24/01/24', 'CID0037', 'Customer 37', 'Los Angeles', 'Dairy', '13', '45.14', '56.42', '733.46', 'Yes', '4', 'Credit Card', 'Quarterly', '08/05/23', '10/05/23']
['23/03/23', 'CID0038', 'Customer 38', 'Houston', 'Bakery', '12', '27.94', '34.92', '419.04', 'Yes', '2', 'Online Payment', 'One Time', '16/01/23', '26/01/23']
['24/12/23', 'CID0039', 'Customer 39', 'Houston', 'Vegetables', '4', '22.94', '28.674', '100.36', 'No', '4', 'Online Payment', 'Weekly', '13/10/23', '15/10/23']
['05/08/23', 'CID0040', 'Customer 40', 'San Antonio', 'Bakery', '2', '61.84', '77.3', '154.6', 'Yes', '2', 'Debit Card', 'Monthly', '15/07/23', '23/07/23']
['24/06/23', 'CID0041', 'Customer 41', 'Philadelphia', 'Vegetables', '13', '7.28', '9.1', '118.3', 'No', '2', 'Debit Card', 'Weekly', '17/04/23', '14/05/23']
['23/05/23', 'CID0042', 'Customer 42', 'Philadelphia', 'Dairy', '14', '19.25', '24.06', '336.84', 'Yes', '2', 'Online Payment', 'Monthly', '27/02/23', '18/03/23']
['21/03/23', 'CID0043', 'Customer 43', 'San Antonio', 'Dairy', '17', '58.7', '73.38', '1247.46', 'Yes', '1', 'Online Payment', 'One Time', '08/03/23', '16/03/23']
['21/04/23', 'CID0044', 'Customer 44', 'Philadelphia', 'Bakery', '9', '44.05', '55.06', '495.54', 'Yes', '1', 'Cash', 'Quarterly', '18/02/23', '19/04/23']
['26/01/24', 'CID0045', 'Customer 45', 'Chicago', 'Bakery', '17', '10.58', '13.23', '224.91', 'Yes', '3', 'Debit Card', 'Weekly', '19/08/23', '21/01/24']
['22/06/23', 'CID0046', 'Customer 46', 'Houston', 'Vegetables', '4', '63.55', '79.443', '317.77', 'Yes', '4', 'Debit Card', 'Weekly', '24/04/23', '27/05/23']
['22/02/23', 'CID0047', 'Customer 47', 'San Antonio', 'Meat', '2', '31.72', '39.65', '79.3', 'Yes', '4', 'Credit Card', 'Quarterly', '20/01/23', '16/02/23']
['17/02/23', 'CID0048', 'Customer 48', 'Houston', 'Vegetables', '6', '59.67', '74.583', '484.79', 'Yes', '1', 'Cash', 'Weekly', '07/02/23', '08/02/23']
['14/07/23', 'CID0049', 'Customer 49', 'New York', 'Bakery', '3', '63.1', '78.88', '236.64', 'Yes', '3', 'Online Payment', 'Monthly', '20/04/23', '26/05/23']
['19/02/23', 'CID0050', 'Customer 50', 'Chicago', 'Beverages', '16', '50.1', '62.63', '1002.08', 'Yes', '1', 'Cash', 'Quarterly', '20/01/23', '27/01/23']
['03/07/23', 'CID0051', 'Customer 51', 'Phoenix', 'Bakery', '6', '39.76', '49.7', '298.2', 'No', '1', 'Online Payment', 'Monthly', '26/05/23', '14/06/23']
['26/06/23', 'CID0052', 'Customer 52', 'Chicago', 'Beverages', '19', '78.38', '97.97', '1861.43', 'Yes', '3', 'Online Payment', 'Monthly', '08/06/23', '11/06/23']
['06/11/23', 'CID0053', 'Customer 53', 'San Antonio', 'Fruits', '7', '11.94', '14.92', '104.44', 'Yes', '3', 'Cash', 'One Time', '31/01/23', '24/02/23']
['16/05/23', 'CID0054', 'Customer 54', 'Phoenix', 'Bakery', '10', '58.12', '72.65', '726.5', 'Yes', '1', 'Debit Card', 'Monthly', '26/01/23', '25/02/23']
['23/01/23', 'CID0055', 'Customer 55', 'New York', 'Fruits', '14', '17.18', '21.472', '289.87', 'Yes', '1', 'Online Payment', 'One Time', '07/01/23', '20/01/23']
['09/01/24', 'CID0056', 'Customer 56', 'San Antonio', 'Meat', '2', '27.33', '34.16', '68.32', 'Yes', '4', 'Cash', 'Weekly', '17/11/23', '27/12/23']
['24/08/23', 'CID0057', 'Customer 57', 'Los Angeles', 'Vegetables', '15', '24.98', '31.22', '468.3', 'Yes', '1', 'Credit Card', 'Weekly', '24/02/23', '02/08/23']
['02/10/23', 'CID0058', 'Customer 58', 'Houston', 'Beverages', '5', '75.78', '94.73', '473.65', 'No', '3', 'Cash', 'One Time', '16/05/23', '10/09/23']
['05/03/23', 'CID0059', 'Customer 59', 'New York', 'Vegetables', '4', '77.4', '96.75', '387', 'Yes', '3', 'Credit Card', 'Monthly', '11/01/23', '15/01/23']
['13/07/23', 'CID0060', 'Customer 60', 'Houston', 'Fruits', '4', '14.97', '18.71', '74.84', 'No', '1', 'Online Payment', 'Quarterly', '10/02/23', '10/03/23']
['10/02/23', 'CID0061', 'Customer 61', 'Philadelphia', 'Beverages', '18', '2.15', '2.69', '48.42', 'No', '1', 'Cash', 'Quarterly', '16/01/23', '31/01/23']
['10/10/23', 'CID0062', 'Customer 62', 'Los Angeles', 'Vegetables', '4', '57.71', '72.14', '288.56', 'Yes', '2', 'Cash', 'One Time', '30/03/23', '29/08/23']
['31/05/23', 'CID0063', 'Customer 63', 'Los Angeles', 'Bakery', '17', '33.67', '42.09', '715.53', 'Yes', '4', 'Credit Card', 'Weekly', '22/05/23', '30/05/23']
['18/11/23', 'CID0064', 'Customer 64', 'New York', 'Dairy', '12', '7.47', '9.34', '112.08', 'No', '3', 'Cash', 'Weekly', '08/02/23', '16/02/23']
['13/11/23', 'CID0065', 'Customer 65', 'Los Angeles', 'Fruits', '8', '49.34', '61.677', '524.25', 'Yes', '3', 'Cash', 'Quarterly', '22/03/23', '30/08/23']
['05/07/23', 'CID0066', 'Customer 66', 'Phoenix', 'Vegetables', '10', '43.79', '54.74', '547.4', 'Yes', '4', 'Online Payment', 'One Time', '01/01/23', '12/05/23']
['23/10/23', 'CID0067', 'Customer 67', 'Los Angeles', 'Fruits', '0', '70.6', '88.254', '44.13', 'No', '4', 'Cash', 'Quarterly', '29/07/23', '10/10/23']
['09/04/23', 'CID0068', 'Customer 68', 'Houston', 'Packaged Foods', '18', '18.5', '23.13', '416.34', 'Yes', '3', 'Debit Card', 'Monthly', '27/02/23', '14/03/23']
['27/12/23', 'CID0069', 'Customer 69', 'Houston', 'Fruits', '18', '32.56', '40.7', '732.6', 'Yes', '3', 'Credit Card', 'Monthly', '19/12/23', '21/12/23']
['05/02/23', 'CID0070', 'Customer 70', 'San Antonio', 'Beverages', '14', '43.58', '54.48', '762.72', 'Yes', '3', 'Cash', 'One Time', '31/01/23', '02/02/23']
['24/01/23', 'CID0071', 'Customer 71', 'Houston', 'Packaged Foods', '15', '63.42', '79.27', '1189.05', 'Yes', '3', 'Credit Card', 'One Time', '10/01/23', '16/01/23']
['05/12/23', 'CID0072', 'Customer 72', 'San Antonio', 'Beverages', '12', '44.09', '55.11', '661.32', 'Yes', '3', 'Credit Card', 'Monthly', '17/01/23', '17/01/23']
['27/04/23', 'CID0073', 'Customer 73', 'Houston', 'Dairy', '4', '49.18', '61.48', '245.92', 'Yes', '3', 'Credit Card', 'Weekly', '30/01/23', '18/04/23']
['31/01/24', 'CID0074', 'Customer 74', 'Phoenix', 'Packaged Foods', '3', '18.4', '23', '69', 'Yes', '1', 'Cash', 'One Time', '28/05/23', '26/08/23']
['29/05/23', 'CID0075', 'Customer 75', 'San Antonio', 'Bakery', '12', '67.82', '84.77', '1017.24', 'Yes', '3', 'Cash', 'Monthly', '14/03/23', '13/04/23']
['10/02/23', 'CID0076', 'Customer 76', 'Chicago', 'Fruits', '7', '34.52', '43.15', '302.05', 'Yes', '2', 'Credit Card', 'Monthly', '30/01/23', '08/02/23']
['30/04/23', 'CID0077', 'Customer 77', 'Philadelphia', 'Vegetables', '11', '11.62', '14.53', '159.83', 'Yes', '1', 'Debit Card', 'Weekly', '10/01/23', '04/03/23']
['21/02/23', 'CID0078', 'Customer 78', 'New York', 'Meat', '1', '53.27', '66.59', '66.59', 'Yes', '1', 'Credit Card', 'Weekly', '13/02/23', '15/02/23']
['14/07/23', 'CID0079', 'Customer 79', 'Houston', 'Fruits', '6', '17.6', '22', '132', 'Yes', '3', 'Debit Card', 'Weekly', '01/03/23', '22/03/23']
['23/05/23', 'CID0080', 'Customer 80', 'Los Angeles', 'Fruits', '8', '7.35', '9.189', '68.92', 'Yes', '3', 'Credit Card', 'Weekly', '09/03/23', '15/05/23']
['21/08/23', 'CID0081', 'Customer 81', 'Houston', 'Dairy', '15', '69.02', '86.27', '1294.05', 'Yes', '2', 'Online Payment', 'Quarterly', '21/07/23', '13/08/23']
['22/11/23', 'CID0082', 'Customer 82', 'Los Angeles', 'Bakery', '19', '37.03', '46.29', '879.51', 'Yes', '3', 'Credit Card', 'Weekly', '17/11/23', '17/11/23']
['06/07/23', 'CID0083', 'Customer 83', 'Philadelphia', 'Meat', '11', '60.04', '75.05', '825.55', 'No', '3', 'Credit Card', 'Quarterly', '31/05/23', '03/07/23']
['25/03/23', 'CID0084', 'Customer 84', 'Philadelphia', 'Packaged Foods', '2', '23.53', '29.41', '58.82', 'Yes', '2', 'Cash', 'One Time', '26/01/23', '01/03/23']
['09/07/23', 'CID0085', 'Customer 85', 'Philadelphia', 'Packaged Foods', '14', '63.04', '78.8', '1103.2', 'Yes', '3', 'Debit Card', 'Monthly', '19/04/23', '22/06/23']
['01/07/23', 'CID0086', 'Customer 86', 'Los Angeles', 'Packaged Foods', '2', '9.31', '11.64', '23.28', 'Yes', '4', 'Online Payment', 'Quarterly', '30/01/23', '08/06/23']
['18/04/23', 'CID0087', 'Customer 87', 'Houston', 'Beverages', '4', '28.74', '35.92', '143.68', 'Yes', '4', 'Debit Card', 'One Time', '11/03/23', '15/04/23']
['10/12/23', 'CID0088', 'Customer 88', 'Philadelphia', 'Beverages', '17', '78.26', '97.82', '1662.94', 'Yes', '3', 'Online Payment', 'One Time', '26/04/23', '01/05/23']
['17/05/23', 'CID0089', 'Customer 89', 'Phoenix', 'Vegetables', '3', '63.6', '79.5', '238.5', 'Yes', '3', 'Credit Card', 'Quarterly', '08/02/23', '29/03/23']
['26/12/23', 'CID0090', 'Customer 90', 'San Antonio', 'Meat', '13', '39.98', '49.98', '649.74', 'Yes', '1', 'Cash', 'One Time', '17/05/23', '26/12/23']
['16/12/23', 'CID0091', 'Customer 91', 'Los Angeles', 'Packaged Foods', '9', '27.45', '34.31', '308.79', 'Yes', '2', 'Cash', 'One Time', '14/03/23', '09/11/23']
['28/11/23', 'CID0092', 'Customer 92', 'Los Angeles', 'Beverages', '7', '69.82', '87.28', '610.96', 'Yes', '1', 'Debit Card', 'Quarterly', '06/02/23', '28/02/23']
['06/02/23', 'CID0093', 'Customer 93', 'Houston', 'Vegetables', '8', '39.39', '49.239', '369.29', 'Yes', '4', 'Cash', 'One Time', '04/01/23', '28/01/23']
['08/11/23', 'CID0094', 'Customer 94', 'Los Angeles', 'Bakery', '11', '60.77', '75.96', '835.56', 'Yes', '1', 'Debit Card', 'Weekly', '26/03/23', '29/06/23']
['22/11/23', 'CID0095', 'Customer 95', 'Los Angeles', 'Vegetables', '2', '60.42', '75.53', '151.06', 'Yes', '1', 'Debit Card', 'Weekly', '07/06/23', '10/08/23']
['29/03/23', 'CID0096', 'Customer 96', 'Philadelphia', 'Beverages', '15', '1.83', '2.29', '34.35', 'Yes', '4', 'Online Payment', 'Monthly', '18/03/23', '29/03/23']
['01/10/23', 'CID0097', 'Customer 97', 'Houston', 'Dairy', '14', '10.45', '13.06', '182.84', 'Yes', '4', 'Debit Card', 'One Time', '28/05/23', '30/05/23']
['09/01/24', 'CID0098', 'Customer 98', 'Philadelphia', 'Dairy', '11', '52.9', '66.13', '727.43', 'Yes', '4', 'Online Payment', 'Monthly', '13/08/23', '12/11/23']
['06/05/23', 'CID0099', 'Customer 99', 'San Antonio', 'Packaged Foods', '3', '13.26', '16.58', '49.74', 'Yes', '1', 'Cash', 'Weekly', '16/01/23', '26/04/23']
['25/03/23', 'CID0100', 'Customer 100', 'San Antonio', 'Dairy', '17', '20.74', '25.92', '440.64', 'Yes', '1', 'Debit Card', 'Weekly', '01/03/23', '03/03/23']
['25/08/23', 'CID0101', 'Customer 101', 'Philadelphia', 'Packaged Foods', '12', '75.75', '94.69', '1136.28', 'Yes', '3', 'Debit Card', 'Weekly', '26/06/23', '18/07/23']
['14/07/23', 'CID0102', 'Customer 102', 'San Antonio', 'Packaged Foods', '15', '44.99', '56.24', '843.6', 'Yes', '1', 'Credit Card', 'One Time', '19/03/23', '18/04/23']
['19/05/23', 'CID0103', 'Customer 103', 'Houston', 'Beverages', '16', '60.16', '75.2', '1203.2', 'Yes', '1', 'Debit Card', 'One Time', '14/04/23', '20/04/23']
['24/11/23', 'CID0104', 'Customer 104', 'New York', 'Dairy', '5', '44.82', '56.02', '280.1', 'Yes', '3', 'Debit Card', 'Weekly', '20/05/23', '15/10/23']
['19/12/23', 'CID0105', 'Customer 105', 'Philadelphia', 'Packaged Foods', '6', '44.38', '55.48', '332.88', 'No', '4', 'Credit Card', 'Monthly', '14/09/23', '17/12/23']
['13/10/23', 'CID0106', 'Customer 106', 'Phoenix', 'Meat', '19', '7.9', '9.87', '187.53', 'Yes', '2', 'Credit Card', 'Monthly', '04/10/23', '09/10/23']
['23/04/23', 'CID0107', 'Customer 107', 'Phoenix', 'Bakery', '5', '27.75', '34.69', '173.45', 'Yes', '3', 'Cash', 'Quarterly', '05/03/23', '13/03/23']
['17/12/23', 'CID0108', 'Customer 108', 'Los Angeles', 'Vegetables', '3', '22.88', '28.6', '85.8', 'Yes', '3', 'Debit Card', 'Weekly', '13/08/23', '18/08/23']
['16/06/23', 'CID0109', 'Customer 109', 'San Antonio', 'Vegetables', '1', '31.5', '39.38', '39.38', 'Yes', '2', 'Cash', 'Monthly', '21/01/23', '21/04/23']
['29/01/24', 'CID0110', 'Customer 110', 'Phoenix', 'Beverages', '6', '63.95', '79.94', '479.64', 'Yes', '3', 'Cash', 'Weekly', '03/11/23', '11/01/24']
['29/01/23', 'CID0111', 'Customer 111', 'Los Angeles', 'Dairy', '15', '30.01', '37.51', '562.65', 'Yes', '2', 'Credit Card', 'Monthly', '02/01/23', '12/01/23']
['28/04/23', 'CID0112', 'Customer 112', 'New York', 'Dairy', '2', '36.35', '45.44', '90.88', 'Yes', '1', 'Online Payment', 'Quarterly', '24/04/23', '25/04/23']
['17/01/23', 'CID0113', 'Customer 113', 'Houston', 'Packaged Foods', '3', '32.03', '40.04', '120.12', 'No', '4', 'Cash', 'Quarterly', '14/01/23', '17/01/23']
['11/06/23', 'CID0114', 'Customer 114', 'Houston', 'Fruits', '17', '7.83', '9.79', '166.43', 'Yes', '1', 'Online Payment', 'Weekly', '24/03/23', '24/05/23']
['25/07/23', 'CID0115', 'Customer 115', 'Houston', 'Packaged Foods', '12', '35.51', '44.39', '532.68', 'No', '4', 'Debit Card', 'Monthly', '04/06/23', '14/07/23']
['18/05/23', 'CID0116', 'Customer 116', 'Phoenix', 'Bakery', '18', '15.97', '19.96', '359.28', 'Yes', '1', 'Credit Card', 'One Time', '06/03/23', '29/03/23']
['03/02/23', 'CID0117', 'Customer 117', 'New York', 'Meat', '15', '15.26', '19.08', '286.2', 'Yes', '3', 'Debit Card', 'Quarterly', '02/01/23', '10/01/23']
['19/04/23', 'CID0118', 'Customer 118', 'Phoenix', 'Vegetables', '12', '7.89', '9.86', '118.32', 'Yes', '3', 'Debit Card', 'Weekly', '12/01/23', '20/01/23']
['18/10/23', 'CID0119', 'Customer 119', 'San Antonio', 'Packaged Foods', '16', '28.79', '35.99', '575.84', 'Yes', '1', 'Credit Card', 'Weekly', '28/04/23', '23/08/23']
['03/01/24', 'CID0120', 'Customer 120', 'Phoenix', 'Fruits', '8', '60.7', '75.87', '606.96', 'Yes', '1', 'Debit Card', 'Monthly', '12/12/23', '13/12/23']
['11/06/23', 'CID0121', 'Customer 121', 'New York', 'Fruits', '21', '24.65', '30.811', '647.03', 'Yes', '3', 'Credit Card', 'Weekly', '28/05/23', '01/06/23']
['19/04/23', 'CID0122', 'Customer 122', 'New York', 'Packaged Foods', '17', '25.26', '31.58', '536.86', 'Yes', '4', 'Online Payment', 'Quarterly', '17/03/23', '29/03/23']
['02/12/23', 'CID0123', 'Customer 123', 'San Antonio', 'Beverages', '8', '51.56', '64.45', '515.6', 'Yes', '4', 'Debit Card', 'Weekly', '11/01/23', '02/02/23']
['13/09/23', 'CID0124', 'Customer 124', 'New York', 'Vegetables', '15', '15.99', '19.99', '299.85', 'Yes', '3', 'Credit Card', 'Weekly', '18/05/23', '27/08/23']
['22/07/23', 'CID0125', 'Customer 125', 'New York', 'Beverages', '14', '71.8', '89.75', '1256.5', 'No', '4', 'Cash', 'One Time', '28/05/23', '09/06/23']

In [ ]:
sales_data = pd.read_csv('/content/Carnids Farm Sales.csv', delimiter=';')

In [ ]:
print(sales_data.describe()) # Print summary statistics of numerical columns ###

          Quantity   Unit Cost   Unit Price  Total Revenue  Delivery Days
count  1000.000000  1000.00000  1000.000000    1000.000000    1000.000000
mean     10.036000    40.47656    50.595761     513.013880       2.714000
std       5.842503    23.29664    29.120737     461.005353       1.091511
min       0.000000     0.42000     0.520000       2.220000       1.000000
25%       5.000000    20.39250    25.492000     137.352500       2.000000
50%      10.000000    41.29500    51.620000     378.130000       3.000000
75%      15.000000    60.89000    76.117500     750.395000       4.000000
max      28.000000    86.23000   107.789000    2594.840000       4.000000

In [ ]:
print(sales_data.info())   # Print a concise summary of the dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Date                 1000 non-null   object
 1   Customer ID          1000 non-null   object
 2   Customer Name        1000 non-null   object
 3   City                 1000 non-null   object
 4   Product Category     1000 non-null   object
 5   Quantity             1000 non-null   int64
 6   Unit Cost            1000 non-null   float64
 7   Unit Price           1000 non-null   float64
 8   Total Revenue        1000 non-null   float64
 9   New Customer         1000 non-null   object
 10  Delivery Days        1000 non-null   int64
 11  Payment Method       1000 non-null   object
 12  Order Frequency      1000 non-null   object
 13  First Purchase Date  1000 non-null   object
 14  Last Purchase Date   1000 non-null   object
dtypes: float64(3), int64(2), object(10)
memory usage: 117.3+ KB
None

In [ ]:
print(sales_data.head())   # Print the first few rows of the dataframe

       Date Customer ID Customer Name         City Product Category  Quantity  \
0  24/11/23     CID0001    Customer 1  San Antonio   Packaged Foods         8
1  27/02/23     CID0002    Customer 2      Houston       Vegetables         6
2  13/01/23     CID0003    Customer 3      Phoenix            Dairy        19
3  15/01/24     CID0004    Customer 4  San Antonio           Fruits         3
4  21/05/23     CID0005    Customer 5      Chicago           Bakery         8

   Unit Cost  Unit Price  Total Revenue New Customer  Delivery Days  \
0      68.28      85.350         682.80          Yes              3
1      16.52      20.646         134.20          Yes              2
2      30.40      38.000         722.00          Yes              1
3      37.15      46.440         139.32           No              3
4      38.68      48.350         386.80          Yes              1

   Payment Method Order Frequency First Purchase Date Last Purchase Date
0     Credit Card       Quarterly            28/01/23           20/04/23
1  Online Payment         Monthly            05/02/23           13/02/23
2  Online Payment         Monthly            05/01/23           12/01/23
3  Online Payment          Weekly            24/12/23           09/01/24
4  Online Payment          Weekly            02/02/23           20/02/23

In [ ]:
sales_data['Date'] = pd.to_datetime(sales_data['Date'])
sales_data['First Purchase Date'] = pd.to_datetime(sales_data['First Purchase Date'])
sales_data['Last Purchase Date'] = pd.to_datetime(sales_data['Last Purchase Date'])

<ipython-input-8-4e16ebc1f367>:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  sales_data['Date'] = pd.to_datetime(sales_data['Date'])
<ipython-input-8-4e16ebc1f367>:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  sales_data['First Purchase Date'] = pd.to_datetime(sales_data['First Purchase Date'])
<ipython-input-8-4e16ebc1f367>:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  sales_data['Last Purchase Date'] = pd.to_datetime(sales_data['Last Purchase Date'])

In [ ]:
print(sales_data.info())   # Print a concise summary of the dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Date                 1000 non-null   datetime64[ns]
 1   Customer ID          1000 non-null   object
 2   Customer Name        1000 non-null   object
 3   City                 1000 non-null   object
 4   Product Category     1000 non-null   object
 5   Quantity             1000 non-null   int64
 6   Unit Cost            1000 non-null   float64
 7   Unit Price           1000 non-null   float64
 8   Total Revenue        1000 non-null   float64
 9   New Customer         1000 non-null   object
 10  Delivery Days        1000 non-null   int64
 11  Payment Method       1000 non-null   object
 12  Order Frequency      1000 non-null   object
 13  First Purchase Date  1000 non-null   datetime64[ns]
 14  Last Purchase Date   1000 non-null   datetime64[ns]
dtypes: datetime64[ns](3), float64(3), int64(2), object(7)
memory usage: 117.3+ KB
None

In [ ]:
sales_data = sales_data.drop_duplicates()

In [ ]:
# Check if 'First Purchase Date' is before 'Last Purchase Date'
inconsistent_dates = sales_data[sales_data['First Purchase Date'] > sales_data['Last Purchase Date']]
print(inconsistent_dates)

          Date Customer ID Customer Name          City Product Category  \
1   2023-02-27     CID0002    Customer 2       Houston       Vegetables
12  2023-07-10     CID0013   Customer 13       Chicago             Meat
15  2023-05-08     CID0016   Customer 16       Chicago        Beverages
25  2023-12-04     CID0026   Customer 26      New York           Fruits
26  2024-02-01     CID0027   Customer 27       Houston   Packaged Foods
..         ...         ...           ...           ...              ...
970 2023-03-03     CID0971  Customer 971   San Antonio           Bakery
973 2024-01-26     CID0974  Customer 974       Phoenix           Fruits
991 2023-04-07     CID0992  Customer 992   San Antonio        Beverages
992 2023-02-04     CID0993  Customer 993   Los Angeles           Bakery
995 2023-12-29     CID0996  Customer 996  Philadelphia             Meat

     Quantity  Unit Cost  Unit Price  Total Revenue New Customer  \
1           6      16.52      20.646         134.20          Yes
12         16      62.50      78.130        1250.08          Yes
15         16      18.33      22.910         366.56          Yes
25         16      24.57      30.712         506.75          Yes
26         13      63.06      78.820        1024.66          Yes
..        ...        ...         ...            ...          ...
970        11      56.79      70.990         780.89          Yes
973        17      36.13      45.160         767.72          Yes
991        11      35.05      43.810         481.91          Yes
992        17      44.13      55.160         937.72          Yes
995        17      40.73      50.910         865.47          Yes

     Delivery Days  Payment Method Order Frequency First Purchase Date  \
1                2  Online Payment         Monthly          2023-05-02
12               3     Credit Card       Quarterly          2023-08-29
15               2  Online Payment       Quarterly          2023-03-29
25               2      Debit Card       Quarterly          2023-10-01
26               4  Online Payment          Weekly          2023-10-23
..             ...             ...             ...                 ...
970              2     Credit Card         Monthly          2023-01-16
973              4      Debit Card       Quarterly          2023-10-04
991              3            Cash          Weekly          2023-06-03
992              3     Credit Card         Monthly          2023-07-01
995              4     Credit Card        One Time          2023-11-10

    Last Purchase Date
1           2023-02-13
12          2023-01-09
15          2023-02-07
25          2023-01-28
26          2023-09-11
..                 ...
970         2023-01-02
973         2023-08-09
991         2023-03-05
992         2023-01-28
995         2023-10-28

[268 rows x 15 columns]

In [ ]:
print(len(inconsistent_dates))

268

In [ ]:
# Calculate the duration between the first and last purchase
sales_data['Customer Relationship Duration'] = (sales_data['Last Purchase Date'] - sales_data['First Purchase Date']).dt.days

In [ ]:
sales_data_cleaned = sales_data[sales_data['First Purchase Date'] <= sales_data['Last Purchase Date']]

In [ ]:
# Verify there are no more inconsistencies in dates
inconsistent_dates_after = sales_data_cleaned[sales_data_cleaned['First Purchase Date'] > sales_data_cleaned['Last Purchase Date']]
print(inconsistent_dates_after)

Empty DataFrame
Columns: [Date, Customer ID, Customer Name, City, Product Category, Quantity, Unit Cost, Unit Price, Total Revenue, New Customer, Delivery Days, Payment Method, Order Frequency, First Purchase Date, Last Purchase Date, Customer Relationship Duration]
Index: []

In [ ]:
print(len(sales_data_cleaned))

732

In [ ]:
# Identify negative values
negative_quantities = sales_data[sales_data['Quantity'] < 0]
print(negative_quantities)

Empty DataFrame
Columns: [Date, Customer ID, Customer Name, City, Product Category, Quantity, Unit Cost, Unit Price, Total Revenue, New Customer, Delivery Days, Payment Method, Order Frequency, First Purchase Date, Last Purchase Date, Customer Relationship Duration]
Index: []

In [ ]:
# Check for negative values in Unit Cost, Unit Price, and Total Revenue
negative_values = sales_data_cleaned[(sales_data_cleaned['Unit Cost'] < 0) |
                                     (sales_data_cleaned['Unit Price'] < 0) |
                                     (sales_data_cleaned['Total Revenue'] < 0)]
print(negative_values)

Empty DataFrame
Columns: [Date, Customer ID, Customer Name, City, Product Category, Quantity, Unit Cost, Unit Price, Total Revenue, New Customer, Delivery Days, Payment Method, Order Frequency, First Purchase Date, Last Purchase Date, Customer Relationship Duration]
Index: []

In [ ]:
print(sales_data_cleaned.info())   # Print a concise summary of the dataframe

<class 'pandas.core.frame.DataFrame'>
Index: 732 entries, 0 to 999
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Date                            732 non-null    datetime64[ns]
 1   Customer ID                     732 non-null    object
 2   Customer Name                   732 non-null    object
 3   City                            732 non-null    object
 4   Product Category                732 non-null    object
 5   Quantity                        732 non-null    int64
 6   Unit Cost                       732 non-null    float64
 7   Unit Price                      732 non-null    float64
 8   Total Revenue                   732 non-null    float64
 9   New Customer                    732 non-null    object
 10  Delivery Days                   732 non-null    int64
 11  Payment Method                  732 non-null    object
 12  Order Frequency                 732 non-null    object
 13  First Purchase Date             732 non-null    datetime64[ns]
 14  Last Purchase Date              732 non-null    datetime64[ns]
 15  Customer Relationship Duration  732 non-null    int64
dtypes: datetime64[ns](3), float64(3), int64(3), object(7)
memory usage: 97.2+ KB
None

In [ ]:
print(sales_data.describe()) # Print summary statistics of numerical columns

                      Date     Quantity   Unit Cost   Unit Price  \
count                 1000  1000.000000  1000.00000  1000.000000
mean   2023-07-20 13:19:12    10.036000    40.47656    50.595761
min    2023-01-01 00:00:00     0.000000     0.42000     0.520000
25%    2023-04-12 00:00:00     5.000000    20.39250    25.492000
50%    2023-07-11 00:00:00    10.000000    41.29500    51.620000
75%    2023-10-22 06:00:00    15.000000    60.89000    76.117500
max    2024-12-01 00:00:00    28.000000    86.23000   107.789000
std                    NaN     5.842503    23.29664    29.120737

       Total Revenue  Delivery Days         First Purchase Date  \
count    1000.000000    1000.000000                        1000
mean      513.013880       2.714000  2023-05-15 17:26:52.800000
min         2.220000       1.000000         2023-01-01 00:00:00
25%       137.352500       2.000000         2023-02-20 00:00:00
50%       378.130000       3.000000         2023-04-24 12:00:00
75%       750.395000       4.000000         2023-08-02 00:00:00
max      2594.840000       4.000000         2024-01-27 00:00:00
std       461.005353       1.091511                         NaN

               Last Purchase Date  Customer Relationship Duration
count                        1000                     1000.000000
mean   2023-06-13 13:53:45.600000                       28.852000
min           2023-01-01 00:00:00                     -333.000000
25%           2023-03-18 00:00:00                      -16.000000
50%           2023-05-29 12:00:00                       27.000000
75%           2023-08-31 00:00:00                       93.250000
max           2024-11-01 00:00:00                      601.000000
std                           NaN                      120.601878

In [ ]:
# Check the number of rows before cleaning
print(f"Original DataFrame size: {len(sales_data)}")
print(f"DataFrame after each cleaning step:")

# After removing date inconsistencies
print(f"Size after date consistency check: {len(sales_data_cleaned)}")

# After removing negative quantities
print(f"Size after removing negative quantities: {len(sales_data_cleaned)}")

Original DataFrame size: 1000
DataFrame after each cleaning step:
Size after date consistency check: 732
Size after removing negative quantities: 732

In [ ]:
# Define the path where you want to save the cleaned data
file_path = '/content/cleaned_sales_data.csv'

# Save the cleaned DataFrame to a CSV file
sales_data_cleaned.to_csv(file_path, index=False)

print(f"Cleaned data saved to {file_path}")

Cleaned data saved to /content/cleaned_sales_data.csv